### ISSUE TITLE
missing v1 - incorrect example in docs?

### ISSUE THREAD

**Issue by szabgab** [surrealdb/setup-surreal#4]
The [documentation](https://surrealdb.com/docs/surrealdb/tutorials/using-github-actions) and also the README.md in this repo suggest `uses: surrealdb/setup-surreal@v1` but `https://github.com/surrealdb/setup-surreal@v1`, the `v1` tag does not exist.

`uses: surrealdb/setup-surreal@v1.0.2` can be found.

**Comment by welpie21** [comment]
Heey @szabgab,

Thank you for reporting this issue, I will have a look into to get this sorted out today.

**Comment by welpie21** [comment]
Heey @szabgab.

I've done some research and found out the `v1` git tag was missing on one of the commits. The `v1` tag has been created this morning. I've tested it on one of my test Github action and don't get the issue when specifying the `@v1`. 

Can I maybe ask you nicely if you could double check for me if the issue has been resolved on your end when only specifying the `@v1` tag instead of `@v1.0.2`?

In waiting for your reply I wish you a great day 😄 

Best regards,

Beau

**Comment by szabgab** [comment]
I can confirm that v1 can be used now. Thank you!
